# Generated by Django 4.1.3 on 2022-12-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bid_end',
            field=models.DateField(),
        ),
    ]
